### ISSUE TITLE
error TS2315: Type 'Generator' is not generic.

### ISSUE THREAD

**Issue by GentileFulvio** [SimonJang/moment-date-range#1]
I got the following error

> Typescript version "~3.2.4"

```
node_modules/@simonja/moment-date-range/lib/index.d.ts:6:85 - error TS2315: Type 'Generator' is not generic.

6 export declare function range(start: Moment, rangeOptions?: Partial<RangeOptions>): Generator<Moment>;
                                                                                      ~~~~~~~~~~~~~~~~~

node_modules/@simonja/moment-date-range/lib/index.d.ts:7:98 - error TS2315: Type 'Generator' is not generic.

7 export declare function range(start: Moment, end: Moment, rangeOptions?: Partial<RangeOptions>): Generator<Moment>;
                                                                                                   ~~~~~~~~~~~~~~~~~
```

**Comment by GentileFulvio** [comment]
This does work in typescript `^3.8.3` so not sure if this should be fixed or the readme should include this requirement

**Comment by SimonJang** [comment]
Need to update the documentation. Will do this asap

**Comment by SimonJang** [comment]
> Need to update the documentation. Will do this asap

@GentileFulvio Will add this is in the next release.

**Comment by SimonJang** [comment]
Documentation has been updated with 0.1.2 🥳
